### PR TITLE
Write function finished, finally.

### PR DESCRIPTION
**Pull request by AlexWezensky**

### CODE REVIEW

**Comment by KasanMoor** [comment]
When i try to import a file i exported, all the pixels are in the wrong place. ~~also can we do this without emiting that a frame is selected?~~

**Comment by KasanMoor** [comment]
I also tried importing the example tan file then exporting it to a new file, then importing it again and the pixels are wonky and the program goes into a "program not responding" state while trying to export the large number of frames. 

Durations are also not being exported correctly. when i try to play an animation that i previously exported it hangs on the first few frames

also after this test I see the value of scrolling through the frames by emitting the frame selected as a sort of exporting progress indicator so I retract my earlier statement. we should leave that in.

**Comment by KasanMoor** [comment]
Alex are you still working on this? I added a template of header info to the tan file. This fixed the offset of the pixels. The biggest issue now is that we dont have frame durations saving correctly. or at all. these changes make it so the playback doesnt freeze anymore but the frames are being added with default durations.

**Comment by AlexWezensky** [comment]
Sorry I took a break to work on other homework. I am now working on getting the duration to write.

**Comment by KasanMoor** [comment]
Almost there. Please look at how the example tan files look. Timestamps start at zero. you are also off by one in different directions depending on if you are at the end of the file or not. try importing the example tan, exporting it, then comparing your save to the original

**Comment by AlexWezensky** [comment]
I'm sorry, I'm not seeing the problem. When I import then export and compare, exerything is the same, the first timestamp, the last timestamp, and the number of frames.

**Comment by KasanMoor** [comment]
Here are the steps i took:
Import title2012.tan
delete the extra first frame because its not actually a part of the animation
saveas test.tan
open both for comparing. here is what i see:
image

image

**Comment by unrelentingfox** [comment]
I'm having the same errors @AlexWezensky 

Import the file "title2012.tan"
Then click "Save As" and enter a name,

When you open that file there are three errors that I see that would cause the file to be unreadable:
1. The time stamp does not start at 00:00.000 like it is supposed to.
2. The time stamps stop after the time reaches 00:09.899 all frames after that do not have any time stamps which means over 90% of the frames do not have time stamps.
3. Each frame has an empty space between them, that is not a part of the .tan format.

You might find it easier to just switch everything to .tan2 format since the time signature is in milliseconds instead of the 00:00.000 format. It's up to you though..

**Pull request merged**
